#!/usr/bin/python -u
# The -u makes output unbuffered, so it will show up immediately
import sys
import socket
import select

# pads the name with null bytes at the end
def pad(name):
    result = '\0' + name
    while len(result) < 108:
        result += '\0'
    return result

def main():
    id = sys.argv[1]
    LAN = sys.argv[2:]
    sockets = []

    # creates sockets and connects to them
    for i in range(len(LAN)):
        s = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
        s.connect(pad(LAN[i]))
        sockets.append(s)

    print "Bridge " + id + " starting up\n"

    while True:
        # Calls select with all the sockets; change the timeout value (1)
        ready, _, _ = select.select(sockets, [], [], 1)

        # Reads from each fo the ready sockets
        for sock in ready:
            data = sock.recv(1500)
            print(data)

if __name__ == '__main__':
    main()
